config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'matches#index'
  resource :user, only: [:show, :edit, :update, :destroy]
  resources :matches, only: [:index, :show]
  resources :counts

  namespace :admin do
  	resources :matches
  	resources :users, only: [:index, :show, :edit, :update, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/count.rb
class Count < ApplicationRecord
	belongs_to :user
	belongs_to :team
end

app/models/countresult.rb
class Countresult < ApplicationRecord
	belongs_to :user
end

app/models/match.rb
class Match < ApplicationRecord
	has_many :teams, inverse_of: :match, dependent: :destroy
	accepts_nested_attributes_for :teams, reject_if: :all_blank, allow_destroy: true

	enum genre: {野球:0,サッカー:1,テニス:2,バスケットボール:3,バレーボール:4,卓球:5,バトミントン:6,eSport:7,その他:8}
	enum match_status: {試合前:0, 試合中:1, 試合終了:2}
end

app/models/team.rb
class Team < ApplicationRecord
	belongs_to :match
  	has_many :counts, dependent: :destroy
  	enum result: { lose: false, win: true }
  	#accepts_nested_attributes_for :counts, reject_if: :all_blank, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :authentication_keys => [:user_name]
  has_many :counts,dependent: :destroy
  has_many :countresults,dependent: :destroy
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
end

app/controllers/admin/matches_controller.rb
class Admin::MatchesController < ApplicationController
	before_action :authenticate_user!
	before_action :only_admin_user

	def index
		@matches = Match.all
	end

	def new
		@match = Match.new
	end

	def show
		@match = Match.find(params[:id])
		@results = Countresult.all
	end

	def create
		match = Match.new(match_params)
		match.save
		redirect_to  admin_matches_path
	end

	def update
    	match = Match.find(params[:id])
    	match.update(matchs_params)
    	if match.match_status == "試合終了"
    		team = Team.find(params[:match][:team_id])
    		team.result = true
    		team.save
    		lose_team = Team.find_by(match_id: match, result: "lose")
    		odds = (lose_team.totalcount / team.totalcount.to_f).round(3)
    		team.counts.each do |count|
    			@result = Countresult.new(user_id: count.user_id, countresult:count.count)
    			@result.countresult = @result.countresult*odds
    			@result.save
    			user = User.find(count.user_id)
    			user.rate += @result.countresult
    			user.rate += count.count
    			user.save
    		end
    		redirect_to admin_match_path(match.id)
    	else
    		redirect_to admin_matches_path
    	end
    end

    def destroy
		@match = Match.find(params[:id])
		@match.destroy
		redirect_to admin_matches_path
	end
	private
		def match_params
			params.require(:match).permit(:genre, :match_name, :match_status, :match_day,
											teams_attributes: [:id, :team_number, :team_name, :team_image, :destroy])
		end

	def only_admin_user
		if current_user.admin?
		else
			redirect_to matches_path
		end
	end

	def matchs_params
		params.require(:match).permit(:match_status)
	end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
	before_action :authenticate_user!
	before_action :only_admin_user

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def only_admin_user
		if current_user.admin?
		else
			redirect_to matches_path
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name, :email])
  end

end

app/controllers/counts_controller.rb
class CountsController < ApplicationController
	before_action :authenticate_login_user

	def create
		@count = Count.new(count_params)
		team = Team.find(params[:count][:team_id])
     	@count.user_id = current_user.id
     	team.totalcount += @count.count
      current_user.rate -= @count.count
  	 	@count.save
      current_user.save
  	 	team.save
  	 	redirect_to matches_path
	end

	private
  def count_params
    params.require(:count).permit(:team_id, :count)
  end

  def authenticate_login_user
    unless :authenticate_user!
    redirect_to products_path
    flash[:notice] = "ログインして下さい"
    end
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

	def index
		@matches = Match.all
	end

	def show
		@match = Match.find(params[:id])
		@team_a = Team.find_by(match_id: @match.id, team_number: 1)
		@team_b = Team.find_by(match_id: @match.id, team_number: 2)
		@count = Count.new
		#@sum_a = @team_a.counts.sum(:count)
		#@sum_b = @team_b.counts.sum(:count)
		@sum_a = @team_a.totalcount
		@sum_b = @team_b.totalcount
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = current_user
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/counts_helper.rb
module CountsHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/matches/_team_fields.html.erb
<div class="nested-fields well well-compact">
  <div class="form-group">
    <%= f.label :No %>
    <%= f.select :team_number, 1...3 %>
    <%= f.label :チーム名 %>
    <%= f.text_field :team_name,placeholder: "チーム名" %>
    <%= link_to_remove_association "チーム削除", f %>
  </div>
</div>

app/views/admin/matches/index.html.erb
<div class="container">
	<div class="back-color">
		<div class="row">
			<div class="col-md-10 col-md-offset-1">
				<h1 class="text-left">試合 一覧</h1>
				<table class="table">
					<thead>
						<tr>
							<th>登録者 ID</th>
							<th>ユーザー名</th>
							<th>試合状況</th>
							<th></th>
							<th></th>
						</tr>
					</thead>
					<tbody class="text-left">
						<% @matches.order(created_at: "desc").each do |match| %>
						<tr>
							<td><%= match.id %></td>
							<td><%= match.match_name %></td>
							<td><%= match.match_status %></td>
							<td><div><%= link_to '試合詳細', admin_match_path(match.id), class: "btn btn-default" %></div></td>
							<td><%= link_to "削除", admin_match_path(match.id), method: :delete,"data-confirm" => "削除しますか？", class: "btn btn-danger" %></td>
						</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

app/views/admin/matches/new.html.erb
<div class="container">
	<div class="row">
		<div class="main col-md-offset-2 col-md-8">
			<div class="panel panel-default">
				<div class="panel-heading"><h2>試合情報 新規登録</h2></div>
				<div class="panel-body">
					<%= form_for ([:admin,@match]) do |f| %>
					<p>
						<%= f.label :スポーツジャンル %>
						<%= f.select :genre, Match.genres.keys %>
					</p>
					<p>
						<%= f.label :大会名 %>
						<%= f.text_field :match_name,placeholder: "大会名", class: "form-control" %>
					</p>
					<p>
						<%= f.label :大会日時 %>
						<%= f.datetime_select :match_day,placeholder: "サムネイル", class: "form-control" %>
					</p>
					<div id="teams">
						<%= f.fields_for :teams do |team| %>
					<%= render 'team_fields', f: team %>
					<% end %>
					</div>
					<div class="disc-add" id="links">
						<%= link_to_add_association 'チーム追加',f, :teams,count:2 %>
					</div>
				</div>
			</div>
		</div>
			<div class="actions row product-new">
				<%= f.submit :試合登録,class: "btn btn-primary col-md-offset-4 col-md-4" %>
					<% end %>
			</div>


	</div>
</div>

app/views/admin/matches/show.html.erb
<div class="container">
  <div class="back-color">
   <div class="row">
    <div class="col-md-10 col-md-offset-1">
     <h1 class="h1-text">試合詳細</h1>
     <div class="row">
      <div class="col-md-5 col-md-offset-1">
        <h2 class="h2-text">試合ID</h2>
        <p><%= @match.id %></p>
        <h2 class="h2-text">ジャンル</h2>
        <p><%= @match.genre %></p>
        <h2 class="h2-text">大会名 日時</h2>
        <p><%= @match.match_name %><br>
          <%= @match.match_day %></p>
          <% if @match.match_status != "試合終了" %>
          <h2 class="h2-text">ステータス</h2>
          <%= form_for([:admin, @match]) do |f| %>
          <%= f.select :match_status, Match.match_statuses.keys %>
          <% @match.teams.each do |team| %>
          <%= f.radio_button :team_id, team.id, {:checked => false} %>
          <%= team.team_name %>
          <% end %>
          <%= f.submit '変更' %>
          <% end %>
          <% end %>
        </div>
        <div class="col-md-5">
          <h2 class="h2-text">BET</h2>
          <table class="table">
          <thead>
            <tr>
              <th>ユーザ名</th>
              <th>BETrate</th>
            </tr>
          </thead>
          <tbody class="text-left">
            <% @results.each do |result| %>
            <% user_id = result.user_id %>
            <% user = User.find(user_id) %>
            <tr>
              <td><%= user.user_name %></td>
              <td><%= result.countresult %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
	<div class="back-color">
		<div class="row">
			<div class="col-md-10 col-md-offset-1">
				<h1 class="text-left">登録者 一覧</h1>
				<table class="table">
					<thead>
						<tr>
							<th>登録者 ID</th>
							<th>ユーザー名</th>
							<th>メールアドレス</th>
							<th></th>
						</tr>
					</thead>
					<tbody class="text-left">
						<% @users.each do |user| %>
						<% next if user.id == 1 %>
						<tr>
							<td><%= user.id %></td>
							<td><%= user.user_name %></td>
							<td><%= user.email %></td>
							<td><div><%= link_to 'ユーザー詳細', admin_user_path(user.id), class: "btn btn-default" %></div></td>
						</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

app/views/admin/users/show.html.erb
<% @user.countresults.each do |result| %>
<%= result.countresult %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookmaker3</title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<header>
  <div class="head">
    <div class="head-title">Bookmaker</div>
    <% if user_signed_in? && current_user.admin == true %>
    <nav class="head_navi">
      <li class="navi-list"><%= link_to 'TOP画面', matches_path %></li>
      <li class="navi-list"><%= link_to '試合 一覧', admin_matches_path %></li>
      <li class="navi-list"><%= link_to 'ユーザ 一覧', admin_users_path %></li>
      <li class="navi-list"><%= link_to "試合登録", new_admin_match_path, data: {"turbolinks" => false} %></li>
      <li class="navi-list"><%= link_to 'ログアウト', destroy_user_session_path , method: :delete %></li>
    </nav>
    <% end %>
  </div>
</header>
<body>
  <div id="wrapper">
    <%= yield %>
<!-- </body> -->
  <footer>
   <p class="footer-text">© Bookmaker3.</p>
 </footer>
</div>
</body>
</html>

app/views/matches/index.html.erb
<div class="body">
	<div class="container">
		<div class="row match">
			<div class="col-lg-8">
				<h1 class="title">MATCHES </h1>
				<div style="border-top: 1px solid gray;">
					<table class="table">
						<thead>
							<tr>
								<th>Sports</th>
								<th>teamA</th>
								<th>teamB</th>
								<th>大会</th>
								<th>試合日時</th>
								<th>試合状況</th>
							</tr>
						</thead>
						<tbody>
							<% @matches.order(created_at: "desc").each do |match| %>
							<tr>
								<% if match.match_status == "試合中" %>
								<td class="item">
									<%= link_to match.genre, match_path(match.id),data: {"turbolinks" => false} %>
								</td>

								<% match.teams.each do |team| %>
								<td class="item">
									<%= link_to team.team_name, match_path(match.id),data: {"turbolinks" => false} %>
								</td>
								<% end %>
								<td class="item">
									<%= link_to match.match_name, match_path(match.id),data: {"turbolinks" => false} %>
								</td>
								<td class="item">
									<%= link_to match.match_day.strftime("%m月 %d日 %H:%M") , match_path(match.id),data: {"turbolinks" => false} %>
								</td>
								<td class="item"><%= match.match_status %></td>
							</tr>

							<% end %>
							<% end %>
						</tbody>
					</table>
				</div>


				<h1 class="title">MATCHES UPCOMING</h1>
				<div style="border-top: 1px solid gray;">
					<table class="table">
						<thead>
							<tr>
								<th>Sports</th>
								<th>teamA</th>
								<th>teamB</th>
								<th>大会</th>
								<th>試合日時</th>
								<th>試合状況</th>
							</tr>
						</thead>
						<tbody>
							<% @matches.order(created_at: "desc").each do |match| %>
							<tr>
								<% if match.match_status == "試合前" %>
								<td class="item">
									<%= link_to match.genre, match_path(match.id),data: {"turbolinks" => false} %>
								</td>

								<% match.teams.each do |team| %>
								<td class="item">
									<%= link_to team.team_name, match_path(match.id),data: {"turbolinks" => false} %>
								</td>
								<% end %>
								<td class="item">
									<%= link_to match.match_name, match_path(match.id),data: {"turbolinks" => false} %>
								</td>
								<td class="item">
									<%= link_to match.match_day.strftime("%m月 %d日 %H:%M") , match_path(match.id),data: {"turbolinks" => false} %>
								</td>
								<td class="item"><%= match.match_status %></td>
							</tr>

							<% end %>
							<% end %>
						</tbody>
					</table>
				</div>


				<h1 class="title">MATCHES HISTORY</h1>
				<div style="border-top: 1px solid gray;">
					<table class="table">
						<thead>
							<tr>
								<th>Sports</th>
								<th>teamA</th>
								<th>teamB</th>
								<th>大会</th>
								<th>試合日時</th>
								<th>試合状況</th>
							</tr>
						</thead>
						<tbody>
							<% @matches.order(created_at: "desc").each do |match| %>
							<tr>
								<% if match.match_status == "試合終了" %>
								<td class="item">
									<%= link_to match.genre, match_path(match.id),data: {"turbolinks" => false} %>
								</td>

								<% match.teams.each do |team| %>
								<td class="item">
									<%= team.result %>
									<%= link_to team.team_name, match_path(match.id),data: {"turbolinks" => false} %>
								</td>
								<% end %>
								<td class="item">
									<%= link_to match.match_name, match_path(match.id),data: {"turbolinks" => false} %>
								</td>
								<td class="item">
									<%= link_to match.match_day.strftime("%m月 %d日 %H:%M") , match_path(match.id),data: {"turbolinks" => false} %>
								</td>
								<td class="item"><%= match.match_status %></td>
							</tr>

							<% end %>
							<% end %>
						</tbody>
					</table>
				</div>
			</div>
			<% if user_signed_in? %>
			<div class="col-lg-4">
				<lu class="side-menu">
					<li class="menu-item btn-edge"><%= link_to 'TOP画面へ', matches_path %></li>
					<li class="menu-item btn-edge"><%= link_to 'マイページ', user_path %></li>
					<li class="menu-item btn-edge"><%= link_to 'ログアウト', destroy_user_session_path , method: :delete %></li>
				</lu>
			</div>
					<% else %>
			<div class="col-lg-4 logout-menu">
				<lu class="side-menu">
					<li class="menu-item btn-edge"><%= link_to '新規登録', new_user_registration_path,data: {"turbolinks" => false} %></li>
					<li class="menu-item btn-edge"><%= link_to 'ログイン', new_user_session_path,data: {"turbolinks" => false} %></li>
				</lu>
			</div>
			<% end %>
		</div>
	</div>
</div>

app/views/matches/show.html.erb
<div class="body">
	<div class="container">
		<div class="row match">
			<div class="col-lg-8">
				<div class="match-time">
					<%= @match.match_day.strftime("%m月 %d日 %H:%M") %>
				</div>
				<h1 class="match-title"><%= @match.match_name %></h1>
				<div class="row match-text">
					<span class="col-lg-5 text-right">
						<%= @team_a.team_name %>
						<span class="winrate-text"><%= (@sum_a / (@sum_a + @sum_b).to_f*100).round(0) %>%</span>
					</span>
					<span class="col-lg-1">vs</span>
					<span class="col-lg-5 text-left">
						<span class="winrate-text"><%= (@sum_b / (@sum_a + @sum_b).to_f*100).round(0) %>%</span>
						<%= @team_b.team_name %>
					</span>
				</div>
				<% if @match.match_status == "試合前" %>
				<%= form_for (@count) do |f| %>
				<div class="radio-btn">
					<% @match.teams.each do |team| %>
					<%= f.radio_button :team_id, team.id, {:checked => true} %>
					<%= team.team_name %>
					<% end %>
					<spend class="rate-btn">
						Betレート
						<%= f.number_field :count, step: 10, min: 0, max: 500 %>
					</spend>
				</div>
				<%= f.submit 'Bet', class: "button"%>
				<% end %>
				<% end %>
			</div>
			<% if user_signed_in? %>
			<div class="col-lg-4">
				<lu class="side-menu">
					<li class="menu-item btn-edge"><%= link_to 'TOP画面へ', matches_path %></li>
					<li class="menu-item btn-edge"><%= link_to 'マイページ', user_path %></li>
					<li class="menu-item btn-edge"><%= link_to 'ログアウト', destroy_user_session_path , method: :delete %></li>
				</lu>
			</div>
			<% else %>
			<div class="col-lg-4 logout-menu">
				<lu class="side-menu">
					<li class="menu-item btn-edge"><%= link_to '新規登録', new_user_registration_path,data: {"turbolinks" => false} %></li>
					<li class="menu-item btn-edge"><%= link_to 'ログイン', new_user_session_path,data: {"turbolinks" => false} %></li>
				</lu>
			</div>
			<% end %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="body">
	<div class="container">
		<div class="row user-show">
			<div class="col-lg-8">
				<h2>ユーザー名</h2>
				<p><%= @user.user_name %></p>
				<h2>レート</h2>
				<p class="rate-text"><%= @user.rate %></p>
			</div>
			<div class="col-lg-4">
				<lu class="side-menu">
					<li class="menu-item btn-edge"><%= link_to 'TOP画面へ', matches_path %></li>
					<li class="menu-item btn-edge"><%= link_to 'マイページ', user_path %></li>
					<li class="menu-item btn-edge"><%= link_to 'ログアウト', destroy_user_session_path , method: :delete %></li>
				</lu>
			</div>
		</div>
	</div>
</div>